import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Button, Card, PageHeader } from '@university-erp/ui-kit';
import { useApplicantJourney } from '../ApplicantJourney.hooks';
export const ProgramExplorerPage = () => {
    const { data, isLoading } = useApplicantJourney();
    if (isLoading)
        return _jsx("div", { style: { color: 'var(--text-secondary)' }, children: "Loading program catalog..." });
    if (!data)
        return null;
    return (_jsxs("div", { className: "fade-in", children: [_jsx(PageHeader, { title: "Program Explorer", subtitle: "Discover your future degree path." }), _jsx("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 'var(--space-6)' }, children: data.programs.map(prog => (_jsxs(Card, { style: { display: 'flex', flexDirection: 'column' }, children: [_jsx("div", { style: { fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 'var(--space-2)' }, children: prog.college }), _jsxs("h3", { style: { margin: '0 0 var(--space-1) 0', color: 'var(--text-primary)' }, children: [prog.degree, " in ", prog.major] }), _jsx("div", { style: { display: 'flex', gap: 'var(--space-2)', flexWrap: 'wrap', margin: 'var(--space-3) 0' }, children: prog.tags.map(tag => _jsx(Badge, { colorScheme: "info", children: tag }, tag)) }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', marginTop: 'auto', marginBottom: 'var(--space-5)' }, children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', fontSize: '0.9rem' }, children: [_jsx("span", { style: { color: 'var(--text-muted)' }, children: "Duration:" }), _jsx("strong", { style: { color: 'var(--text-secondary)' }, children: prog.duration })] }), _jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', fontSize: '0.9rem' }, children: [_jsx("span", { style: { color: 'var(--text-muted)' }, children: "Intake:" }), _jsx("strong", { style: { color: 'var(--text-secondary)' }, children: prog.intake })] }), _jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', fontSize: '0.9rem' }, children: [_jsx("span", { style: { color: 'var(--text-muted)' }, children: "Est. Tuition:" }), _jsx("strong", { style: { color: 'var(--text-secondary)' }, children: prog.tuitionEstimate })] })] }), _jsx(Button, { variant: "primary", style: { width: '100%' }, children: "View Requirements" })] }, prog.id))) })] }));
};
