import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import { EmployeeManagementPage } from '../features/EmployeeManagement/EmployeeManagement.page';
import { PurchaseOrdersPage } from '../features/PurchaseOrders/PurchaseOrders.page';
import { StockManagementPage } from '../features/StockManagement/StockManagement.page';
import { AssetRegistryPage } from '../features/AssetRegistry/AssetRegistry.page';
import { FleetManagementPage } from '../features/FleetManagement/FleetManagement.page';
import { CanteenOrdersPage } from '../features/CanteenOrders/CanteenOrders.page';
import { FacilityBookingPage } from '../features/FacilityBooking/FacilityBooking.page';
const AppShell = ({ children }) => (_jsxs("div", { className: "flex h-screen bg-gray-50", children: [_jsxs("nav", { className: "w-64 bg-slate-900 text-white p-4", children: [_jsx("div", { className: "text-xl font-bold mb-8", children: "Admin Portal" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { className: "pt-2 text-gray-400 text-xs uppercase font-bold", children: "Core Admin" }), _jsx("li", { children: _jsx(Link, { to: "/hr/employees", className: "block p-2 rounded hover:bg-slate-800", children: "Human Resources" }) }), _jsx("li", { children: _jsx(Link, { to: "/procurement/orders", className: "block p-2 rounded hover:bg-slate-800", children: "Procurement" }) }), _jsx("li", { children: _jsx(Link, { to: "/inventory/stock", className: "block p-2 rounded hover:bg-slate-800", children: "Inventory" }) }), _jsx("li", { children: _jsx(Link, { to: "/assets/registry", className: "block p-2 rounded hover:bg-slate-800", children: "Asset Management" }) }), _jsx("li", { className: "pt-4 text-gray-400 text-xs uppercase font-bold", children: "Campus Life" }), _jsx("li", { children: _jsx(Link, { to: "/transport/fleet", className: "block p-2 rounded hover:bg-slate-800", children: "Fleet Management" }) }), _jsx("li", { children: _jsx(Link, { to: "/canteen/orders", className: "block p-2 rounded hover:bg-slate-800", children: "Canteen Orders" }) }), _jsx("li", { children: _jsx(Link, { to: "/facilities/booking", className: "block p-2 rounded hover:bg-slate-800", children: "Facility Booking" }) })] })] }), _jsx("main", { className: "flex-1 overflow-auto", children: children })] }));
export const Routing = () => {
    return (_jsx(BrowserRouter, { children: _jsx(AppShell, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/hr/employees", element: _jsx(EmployeeManagementPage, {}) }), _jsx(Route, { path: "/procurement/orders", element: _jsx(PurchaseOrdersPage, {}) }), _jsx(Route, { path: "/inventory/stock", element: _jsx(StockManagementPage, {}) }), _jsx(Route, { path: "/assets/registry", element: _jsx(AssetRegistryPage, {}) }), _jsx(Route, { path: "/transport/fleet", element: _jsx(FleetManagementPage, {}) }), _jsx(Route, { path: "/canteen/orders", element: _jsx(CanteenOrdersPage, {}) }), _jsx(Route, { path: "/facilities/booking", element: _jsx(FacilityBookingPage, {}) }), _jsx(Route, { path: "*", element: _jsx("div", { className: "p-6", children: "Select a module from the sidebar." }) })] }) }) }));
};
