server {
    listen 80;
    server_name __API_DOMAIN__;

    include snippets/security-headers.conf;
    include snippets/rate-limit.conf;

    location / {
        set $api_upstream universityerp-api:__API_INTERNAL_PORT__;
        proxy_pass http://$api_upstream;
        include snippets/proxy-common.conf;
    }
}
