server {
    listen 80;
    listen 5176;
    server_name __FINANCE_DOMAIN__;
    root /var/www/finance-console;

    include snippets/security-headers.conf;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
