server {
    listen 80;
    listen 5179;
    server_name __LIBRARY_DOMAIN__;
    root /var/www/library-portal;

    include snippets/security-headers.conf;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
