server {
    listen 80;
    listen 5180;
    server_name __LMS_DOMAIN__;
    root /var/www/lms-web;

    include snippets/security-headers.conf;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
