server {
    listen 80;
    server_name lms.university.edu;
    root /var/www/lms-web;

    include snippets/security-headers.conf;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
