<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="sqlite-net-sqlcipher" Version="1.9.172" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.8" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlcipher" Version="2.1.8" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LmsOffline.Domain\LmsOffline.Domain.csproj" />
    <ProjectReference Include="..\LmsOffline.Application\LmsOffline.Application.csproj" />
  </ItemGroup>

</Project>
