import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button, Card, PageHeader } from '@university-erp/ui-kit';
import { useState } from 'react';
export const EligibilityCheckerPage = () => {
    const [step, setStep] = useState(1);
    const [applicantType, setApplicantType] = useState(null);
    return (_jsxs("div", { className: "fade-in", children: [_jsx(PageHeader, { title: "Eligibility Checker", subtitle: "Let's find the right admission path for you." }), _jsxs(Card, { style: { maxWidth: '600px', margin: '0 auto' }, children: [step === 1 && (_jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' }, children: [_jsx("h3", { style: { margin: 0, color: 'var(--text-primary)' }, children: "1. What type of applicant are you?" }), _jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }, children: ['High School Graduate (Freshman)', 'College Transferee', 'International Student', 'Returning Student'].map(type => (_jsxs("label", { style: {
                                        display: 'flex', alignItems: 'center', gap: 'var(--space-3)',
                                        padding: 'var(--space-4)',
                                        border: `1px solid ${applicantType === type ? 'var(--brand-primary)' : 'var(--border-subtle)'}`,
                                        borderRadius: 'var(--radius-md)',
                                        backgroundColor: applicantType === type ? 'var(--bg-surface)' : 'transparent',
                                        cursor: 'pointer',
                                        transition: 'all 0.2s'
                                    }, children: [_jsx("input", { type: "radio", name: "applicantType", value: type, checked: applicantType === type, onChange: () => setApplicantType(type), style: { cursor: 'pointer' } }), _jsx("span", { style: { fontWeight: 500, color: 'var(--text-primary)' }, children: type })] }, type))) }), _jsx(Button, { variant: "primary", onClick: () => setStep(2), disabled: !applicantType, children: "Continue" })] })), step === 2 && (_jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' }, children: [_jsx("h3", { style: { margin: 0, color: 'var(--text-primary)' }, children: "2. Eligibility Confirmed!" }), _jsxs("p", { style: { color: 'var(--text-secondary)' }, children: ["Based on your profile as a ", _jsx("strong", { children: applicantType }), ", you are eligible to apply for our undergraduate programs."] }), _jsxs("div", { style: { backgroundColor: 'var(--info-bg)', padding: 'var(--space-4)', borderRadius: 'var(--radius-md)', color: 'var(--text-primary)' }, children: [_jsx("h4", { style: { margin: '0 0 var(--space-2) 0' }, children: "Required Documents you will need:" }), _jsxs("ul", { style: { margin: 0, paddingLeft: 'var(--space-4)', color: 'var(--text-secondary)' }, children: [_jsx("li", { children: "Birth Certificate" }), _jsx("li", { children: applicantType === 'High School Graduate (Freshman)' ? 'Form 138 (Report Card)' : 'Transcript of Records' }), _jsx("li", { children: "Certificate of Good Moral Character" }), _jsx("li", { children: "2x2 ID Photo" })] })] }), _jsxs("div", { style: { display: 'flex', gap: 'var(--space-3)', marginTop: 'var(--space-2)' }, children: [_jsx(Button, { variant: "outline", onClick: () => setStep(1), style: { flex: 1 }, children: "Back" }), _jsx(Button, { variant: "primary", style: { flex: 2 }, children: "Start Application Wizard" })] })] }))] })] }));
};
