import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, Button, PageHeader } from '@university-erp/ui-kit';
import { useMfaVerification } from './MfaVerification.hooks';
export default function MfaVerification() {
    const [code, setCode] = useState('');
    const [error, setError] = useState('');
    const mfaMutation = useMfaVerification();
    const navigate = useNavigate();
    const handleVerify = async (e) => {
        e.preventDefault();
        try {
            await mfaMutation.mutateAsync(code);
            navigate('/');
        }
        catch {
            setError('Invalid verification code or failed to verify.');
        }
    };
    return (_jsxs("div", { style: { maxWidth: '400px', margin: '4rem auto' }, children: [_jsx(PageHeader, { title: "2-Step Verification" }), _jsxs(Card, { gradient: true, style: { marginTop: '2rem' }, children: [_jsxs("div", { style: { textAlign: 'center', marginBottom: '1.5rem' }, children: [_jsx("div", { style: { fontSize: '3rem', marginBottom: '1rem' }, children: "\uD83D\uDD10" }), _jsx("p", { style: { color: '#ccc', fontSize: '0.95rem' }, children: "Enter the 6-digit verification code generated by your Authenticator app." })] }), _jsxs("form", { onSubmit: handleVerify, style: { display: 'flex', flexDirection: 'column', gap: '1rem' }, children: [_jsxs("div", { children: [_jsx("input", { type: "text", value: code, onChange: (e) => {
                                            setCode(e.target.value.replace(/\D/g, '').slice(0, 6));
                                            setError('');
                                        }, placeholder: "000000", required: true, style: {
                                            width: '100%', padding: '1rem', borderRadius: '4px',
                                            background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)',
                                            color: 'white', fontSize: '1.5rem', textAlign: 'center', letterSpacing: '0.5rem'
                                        } }), error && _jsx("div", { style: { color: 'hsl(0, 70%, 70%)', fontSize: '0.85rem', marginTop: '0.5rem', textAlign: 'center' }, children: error })] }), _jsx(Button, { variant: "primary", style: { width: '100%', marginTop: '0.5rem' }, disabled: mfaMutation.isPending || code.length !== 6, children: mfaMutation.isPending ? 'Verifying...' : 'Verify Code' })] }), _jsx("div", { style: { textAlign: 'center', fontSize: '0.85rem', marginTop: '1.5rem' }, children: _jsx("a", { href: "/login", style: { color: 'hsl(220, 90%, 75%)', textDecoration: 'none' }, children: "Back to Sign In" }) })] })] }));
}
