import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, Button, PageHeader } from '@university-erp/ui-kit';
import { useMfaVerification } from './MfaVerification.hooks';

export default function MfaVerification() {
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const mfaMutation = useMfaVerification();
  const navigate = useNavigate();

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const isValid = await mfaMutation.mutateAsync(code);
      if (isValid) {
        navigate('/');
      } else {
        setError('Invalid verification code.');
      }
    } catch {
      setError('Failed to verify code.');
    }
  };

  return (
    <div style={{ maxWidth: '400px', margin: '4rem auto' }}>
      <PageHeader title="2-Step Verification" />
      
      <Card gradient style={{ marginTop: '2rem' }}>
        <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>🔐</div>
          <p style={{ color: '#ccc', fontSize: '0.95rem' }}>
            Enter the 6-digit verification code generated by your Authenticator app.
          </p>
        </div>

        <form onSubmit={handleVerify} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <input 
              type="text" 
              value={code}
              onChange={(e) => {
                setCode(e.target.value.replace(/\D/g, '').slice(0, 6));
                setError('');
              }}
              placeholder="000000"
              required
              style={{
                width: '100%', padding: '1rem', borderRadius: '4px',
                background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)', 
                color: 'white', fontSize: '1.5rem', textAlign: 'center', letterSpacing: '0.5rem'
              }}
            />
            {error && <div style={{ color: 'hsl(0, 70%, 70%)', fontSize: '0.85rem', marginTop: '0.5rem', textAlign: 'center' }}>{error}</div>}
          </div>
          
          <Button variant="primary" style={{ width: '100%', marginTop: '0.5rem' }} disabled={mfaMutation.isPending || code.length !== 6}>
            {mfaMutation.isPending ? 'Verifying...' : 'Verify Code'}
          </Button>
        </form>

        <div style={{ textAlign: 'center', fontSize: '0.85rem', marginTop: '1.5rem' }}>
          <a href="/login" style={{ color: 'hsl(220, 90%, 75%)', textDecoration: 'none' }}>Back to Sign In</a>
        </div>
      </Card>
    </div>
  );
}
