namespace LearningManagement.Application.Abstractions;

using System;

public interface IScheduleTokenVerifier
{
    /// <summary>
    /// Verifies that the token generated by the client during an offline exam matches 
    /// the cryptographic signature expected by the server to prevent time-tampering.
    /// </summary>
    bool VerifyScheduleToken(string token, Guid assessmentId, Guid studentId);

    /// <summary>
    /// Cryptographically validates the offline session signature to prevent system clock spoofing.
    /// </summary>
    bool VerifyOfflineSessionSignature(string outboxId, DateTime submittedAtUtc);
}