import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Card, PageHeader } from '@university-erp/ui-kit';
import { useStudentProfile } from './StudentProfile.hooks';
export const StudentProfilePage = () => {
    const { data: profile, isLoading, isError } = useStudentProfile();
    if (isLoading)
        return _jsx("div", { style: { color: 'var(--text-secondary)' }, children: "Loading profile data..." });
    if (isError || !profile)
        return _jsx("div", { style: { color: 'var(--danger-text)' }, children: "Failed to load student profile." });
    return (_jsxs("div", { className: "fade-in", children: [_jsx(PageHeader, { title: "My Profile" }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 'var(--space-6)' }, children: [_jsxs(Card, { children: [_jsxs("h2", { style: { margin: '0 0 var(--space-2) 0', fontSize: '1.25rem' }, children: [profile.firstName, " ", profile.lastName] }), _jsx("p", { style: { color: 'var(--text-secondary)', margin: '0 0 var(--space-5) 0', fontSize: '0.95rem' }, children: profile.email }), _jsx("div", { style: { borderTop: '1px solid var(--border-subtle)', paddingTop: 'var(--space-4)' }, children: _jsxs("p", { style: { color: 'var(--text-secondary)', margin: 0, fontSize: '0.875rem' }, children: ["Student ID: ", _jsx("strong", { style: { color: 'var(--text-primary)' }, children: profile.studentNumber })] }) })] }), _jsxs(Card, { children: [_jsx("h2", { style: { margin: '0 0 var(--space-4) 0', fontSize: '1.1rem' }, children: "Academic Standing" }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }, children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [_jsx("span", { style: { color: 'var(--text-secondary)', fontSize: '0.9rem' }, children: "Program" }), _jsx("strong", { style: { color: 'var(--text-primary)', fontSize: '0.9rem', textAlign: 'right' }, children: profile.program })] }), _jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [_jsx("span", { style: { color: 'var(--text-secondary)', fontSize: '0.9rem' }, children: "Status" }), _jsx(Badge, { colorScheme: "success", children: profile.enrollmentStatus })] }), _jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, children: [_jsx("span", { style: { color: 'var(--text-secondary)', fontSize: '0.9rem' }, children: "CGPA" }), _jsx("strong", { style: { color: 'var(--text-primary)', fontSize: '0.9rem' }, children: profile.academicStanding })] })] })] })] })] }));
};
