import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { financePaymentSessionApi, PaymentSessionDto } from '@university-erp/api-clients';
import { useAuth } from '@university-erp/auth-sdk';

// Fetch all payment sessions generated by students
export const useAllPaymentSessions = () => {
    return useQuery({
        queryKey: ['finance', 'payment-sessions'],
        queryFn: () => financePaymentSessionApi.getAllSessions()
    });
};

// Reconcile a session (mark as Paid)
export const useReconcilePayment = () => {
    const queryClient = useQueryClient();
    const { identity } = useAuth();

    return useMutation({
        mutationFn: ({ sessionId, remarks }: { sessionId: string, remarks: string }) => 
            financePaymentSessionApi.reconcileSession(sessionId, { 
                cashierId: identity?.id || 'Cashier-Admin', 
                remarks 
            }),
        onSuccess: () => {
            // Instantly refresh the payment queue and the billing tables
            queryClient.invalidateQueries({ queryKey: ['finance', 'payment-sessions'] });
            queryClient.invalidateQueries({ queryKey: ['finance', 'student-billings'] });
            alert("Payment successfully reconciled and applied to student ledger!");
        },
        onError: (error: any) => {
            console.error("Reconciliation failed:", error);
            alert("Failed to reconcile payment. Please check system logs.");
        }
    });
};
